stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: "registry.gitlab.com/your_project/helloworld"

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest
  only:
    - main

test:
  stage: test
  script:
    - kubectl apply -f k8s/test-deployment.yaml
    - sleep 5
    - ERROR_LOG=$(kubectl logs -l app=helloworld -n test || true)
    - echo $ERROR_LOG
    - if [[ ! -z "$ERROR_LOG" ]]; then
      echo "Sending error to WebSocket server...";
      echo "$ERROR_LOG" | websocat ws://websocket-server-ip:8765;
      fi
  only:
    - main
  allow_failure: true # Allow pipeline to continue after failure

deploy:
  stage: deploy
  script:
    - kubectl apply -f k8s/prod-deployment.yaml
  only:
    - main
