apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-prod
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: ghcr.io/olugbedu/websocket-automation/helloworld:fixed
